login:
  username: "hello"
  password: "world"
  role: "USER"
spring:
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    cluster:
      nodes: localhost:30001
    host: localhost
    port: 30001
